spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: bestuser
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 5343